[Interface]
PrivateKey = {{WG_PHONE_PRIVATE_KEY}}
Address = 10.66.66.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = {{WG_SERVER_PUBLIC_KEY}}
AllowedIPs = 10.66.66.1/32
Endpoint = {{WG_ENDPOINT_HOST}}:{{WG_ENDPOINT_PORT}}
PersistentKeepalive = 25
